# Generated by Django 4.1.7 on 2023-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.IntegerField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
