# Generated by Django 4.1.7 on 2023-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
    ]
